# example for 1.0 cod2 server
version: '3.7'
services:
  myserver:
    image: lonsofore/cod2:1.0
    container_name: myserver
    restart: always
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - ~/cod2/myserver:/cod2/myserver
      - ~/cod2/main:/cod2/main
      - ~/cod2/Library:/cod2/.callofduty2/myserver/Library
    environment:
     PARAMS: "+set fs_homepath /cod2/.callofduty2/ +set fs_game myserver +set dedicated 2 +set net_port 28960 +exec myserver.cfg"
     CHECK_PORT: 28960
